"use strict";
const RACE_DATA_PATH="./data/races.json";
let raceState={all:[],filtered:[],lastFocusedElement:null};
document.addEventListener("DOMContentLoaded",initRacePage);
async function initRacePage(){const list=document.querySelector("[data-race-list]");if(!list)return;bindRaceModal();bindRaceFilters();try{const payload=await RF.loadJSON(RACE_DATA_PATH);const source=Array.isArray(payload)?payload:(payload.races||[]);const upcoming=source.filter(race=>getDayDifference(race.date)>=0);raceState.all=upcoming.map((race,index)=>({...race,__rfKey:`race-${index}-${race.roadrunNo||race.id||""}`})).sort((a,b)=>String(a.date).localeCompare(String(b.date))||String(a.name||"").localeCompare(String(b.name||""),"ko"));raceState.filtered=[...raceState.all];fillRegionOptions();renderSummary(payload.metadata||{});renderRaceList()}catch(error){console.error(error);list.innerHTML=`<div class="race-empty"><h3>대회 데이터를 불러오지 못했습니다.</h3><p>${RF.esc(error.message||"data/races.json을 확인해 주세요.")}</p></div>`}}
function normalize(v){return String(v||"").toLowerCase().replace(/\s+/g,"").trim()}
function bindRaceFilters(){const search=document.querySelector("[data-race-search]"),region=document.querySelector("[data-race-region]"),reset=document.querySelector("[data-race-reset]");const apply=()=>{const q=normalize(search?.value),r=region?.value||"";raceState.filtered=raceState.all.filter(x=>{const text=normalize([x.name,x.region,x.venue,x.organizer,...(x.distances||[])].filter(Boolean).join(" "));return(!q||text.includes(q))&&(!r||x.region===r)});renderRaceList()};search?.addEventListener("input",apply);region?.addEventListener("change",apply);reset?.addEventListener("click",()=>{if(search)search.value="";if(region)region.value="";apply()})}
function fillRegionOptions(){const s=document.querySelector("[data-race-region]");if(!s)return;[...new Set(raceState.all.map(x=>x.region).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"ko")).forEach(r=>s.insertAdjacentHTML("beforeend",`<option value="${RF.esc(r)}">${RF.esc(r)}</option>`))}
function renderSummary(meta){const el=document.querySelector("[data-race-summary]");if(!el)return;const regions=new Set(raceState.all.map(x=>x.region).filter(Boolean)).size;el.innerHTML=`<div><strong>${raceState.all.length}</strong><span>예정 대회</span></div><div><strong>${raceState.all.filter(x=>getDayDifference(x.date)===0).length}</strong><span>오늘 대회</span></div><div><strong>${regions}</strong><span>개최 지역</span></div><div><strong>${RF.esc(meta.updatedAt||"2026-07-11")}</strong><span>정보 기준일</span></div>`}
function renderRaceList(){const list=document.querySelector("[data-race-list]"),count=document.querySelector("[data-race-count]");if(count)count.textContent=`${raceState.filtered.length}개`;if(!raceState.filtered.length){list.innerHTML='<div class="race-empty"><h3>조건에 맞는 대회가 없습니다.</h3></div>';return}const groups=new Map();raceState.filtered.forEach(r=>{const m=r.date.slice(5,7);if(!groups.has(m))groups.set(m,[]);groups.get(m).push(r)});list.innerHTML=[...groups].map(([m,rs])=>`<section class="race-month-group"><header class="race-month-heading"><h2>${Number(m)}월</h2><span>${rs.length}개 대회</span></header><div class="race-month-list">${rs.map(renderRaceRow).join("")}</div></section>`).join("");const map=new Map(raceState.all.map(r=>[r.__rfKey,r]));list.querySelectorAll("[data-race-key]").forEach(btn=>btn.addEventListener("click",()=>{const r=map.get(btn.dataset.raceKey);if(r)openRaceModal(r,btn)}))}
function renderRaceRow(r){const d=getDdayInfo(r.date),place=[r.region,r.venue].filter(Boolean).join(" · ");return`<button class="race-row" type="button" data-race-key="${RF.esc(r.__rfKey)}"><span class="race-date-box"><strong>${r.date.slice(8,10)}</strong><span>${Number(r.date.slice(5,7))}월</span></span><span class="race-main"><span class="race-topline"><span class="race-dday ${d.className}">${RF.esc(d.label)}</span><span class="race-region">${RF.esc(r.region||"-")}</span></span><strong class="race-title">${RF.esc(r.name)}</strong><span class="race-meta"><span>📅 ${RF.esc(formatDate(r.date))}</span><span class="race-place">📍 ${RF.esc(place)}</span></span><span class="race-distances">${(r.distances||[]).map(x=>`<span>${RF.esc(x)}</span>`).join("")}</span></span><span class="race-row-side"><time>${RF.esc(formatShortDate(r.date))}</time><span class="race-detail-label">상세보기 →</span></span></button>`}
function bindRaceModal(){document.querySelectorAll("[data-race-close]").forEach(x=>x.addEventListener("click",closeRaceModal));document.addEventListener("keydown",e=>{if(e.key==="Escape")closeRaceModal()})}
function openRaceModal(r,trigger){const modal=document.querySelector("[data-race-modal]"),title=document.querySelector("[data-race-modal-title]"),subtitle=document.querySelector("[data-race-modal-subtitle]"),dday=document.querySelector("[data-race-modal-dday]"),body=document.querySelector("[data-race-modal-body]"),actions=document.querySelector("[data-race-modal-actions]");if(!modal||!body)return;raceState.lastFocusedElement=trigger;title.textContent=r.name;subtitle.textContent=[r.region,r.venue].filter(Boolean).join(" · ");dday.textContent=getDdayInfo(r.date).label;const items=[["대회 일시",`${formatDate(r.date)}${r.time?` · ${r.time}`:""}`],["지역 · 장소",[r.region,r.venue].filter(Boolean).join(" · ")||"-"],["개최 종목",(r.distances||[]).join(", ")||"-"],["주최단체",r.organizer||"-"],["전화번호",r.phone||"-"],["이메일",r.email||"-"],["접수기간",r.registrationPeriod||"상세 홈페이지 참고"]];body.innerHTML=items.map(([k,v])=>`<div><dt>${RF.esc(k)}</dt><dd>${RF.esc(v)}</dd></div>`).join("")+ (r.description?`<div class="race-description"><dt>대회 소개</dt><dd>${RF.esc(r.description)}</dd></div>`:"");const url=getRaceRegistrationUrl(r);actions.innerHTML=url?`<a class="race-official-btn" href="${RF.esc(url)}" target="_blank" rel="noopener noreferrer">홈페이지 바로가기</a>`:'<p class="race-link-unavailable">홈페이지 주소가 등록되지 않았습니다.</p>';modal.classList.add("is-open");modal.setAttribute("aria-hidden","false");document.body.classList.add("race-modal-open")}
function getRaceRegistrationUrl(r){for(const v of[r.entryUrl,r.officialUrl,r.homepage,r.registrationUrl]){if(!v)continue;try{const u=new URL(v,location.href);if(["http:","https:"].includes(u.protocol))return u.href}catch{}}return""}
function closeRaceModal(){const m=document.querySelector("[data-race-modal]");if(!m?.classList.contains("is-open"))return;m.classList.remove("is-open");m.setAttribute("aria-hidden","true");document.body.classList.remove("race-modal-open");raceState.lastFocusedElement?.focus?.()}
function getDayDifference(date){const now=new Date(),today=new Date(now.getFullYear(),now.getMonth(),now.getDate()),target=new Date(`${date}T00:00:00`);return Math.round((target-today)/86400000)}
function getDdayInfo(date){const n=getDayDifference(date);return n>0?{label:`D-${n}`,className:"is-upcoming"}:n===0?{label:"D-DAY",className:"is-today"}:{label:`D+${Math.abs(n)}`,className:"is-past"}}
function formatDate(v){const [y,m,d]=String(v).split("-");return`${y}년 ${Number(m)}월 ${Number(d)}일`}
function formatShortDate(v){const[,m,d]=String(v).split("-");return`${Number(m)}.${Number(d)}`}
