"use strict";
const cfg={
 shoes:{title:"러닝화",path:"../data/shoes.json",name:x=>`${x.brand||""} ${x.modelKo||x.modelEn||"이름 없음"}`,sub:x=>x.id||"",fields:[["id","ID/slug","text"],["brand","브랜드","text"],["modelKo","한글 모델명","text"],["modelEn","영문 모델명","text"],["image.src","이미지 경로","text"],["primaryUse","주용도","select","daily|training|race|stability"],["published","공개","checkbox"]]},
 races:{title:"대회",path:"../data/races.json",name:x=>x.name||"이름 없음",sub:x=>`${x.date||"날짜 미정"} · ${x.region||"지역 미정"}`,fields:[["id","ID","text"],["name","대회명","text"],["date","개최일","date"],["region","지역","text"],["location","장소","text"],["distances","종목(쉼표 구분)","text"],["officialUrl","공식/신청 URL","url"],["published","공개","checkbox"]]},
 courses:{title:"코스",path:"../data/courses.json",name:x=>x.name||x.title||"이름 없음",sub:x=>`${x.region||"지역 미정"} · ${x.distanceKm||x.distance||"거리 미정"}`,fields:[["id","ID","text"],["name","코스명","text"],["region","지역","text"],["distanceKm","거리(km)","number"],["level","난이도","select","easy|normal|hard"],["mapUrl","지도 URL","url"],["description","설명","textarea"],["published","공개","checkbox"]]}
};
let type="shoes",rows=[],editing=null;
const $=s=>document.querySelector(s), get=(o,p)=>p.split('.').reduce((a,k)=>a?.[k],o), set=(o,p,v)=>{const ks=p.split('.');let a=o;ks.slice(0,-1).forEach(k=>a=a[k]??={});a[ks.at(-1)]=v};
async function load(){rows=await RFContentStore.seed(type,cfg[type].path);render()}
function render(){const q=$("#search").value.trim().toLowerCase();const view=rows.filter(x=>JSON.stringify(x).toLowerCase().includes(q));$("#entityTitle").textContent=cfg[type].title+" 관리";$("#stats").innerHTML=`<span>전체 <b>${rows.length}</b></span><span>공개 <b>${rows.filter(x=>x.published!==false&&x.status!=="deleted").length}</b></span>`;$("#list").innerHTML=view.map((x,i)=>`<article class="row">${type==='shoes'&&get(x,'image.src')?`<img src="../${get(x,'image.src').replace('./','')}" alt="">`:'<div></div>'}<div><h3>${esc(cfg[type].name(x))}</h3><p>${esc(cfg[type].sub(x))}${x.published===false?' · 비공개':''}</p></div><div class="row-actions"><button data-edit="${i}">수정</button><button data-toggle="${i}">${x.published===false?'공개':'숨김'}</button><button data-delete="${i}">삭제</button></div></article>`).join('')||'<p>항목이 없습니다.</p>'}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function openEditor(index=null){editing=index;const row=index===null?{published:true,id:crypto.randomUUID?.()||String(Date.now())}:structuredClone(rows[index]);$("#editorTitle").textContent=index===null?'새 '+cfg[type].title:cfg[type].title+' 수정';$("#fields").innerHTML=cfg[type].fields.map(([key,label,kind,opts])=>{const v=get(row,key);if(kind==='checkbox')return `<label><span>${label}</span><input name="${key}" type="checkbox" ${v!==false?'checked':''}></label>`;if(kind==='textarea')return `<label class="wide"><span>${label}</span><textarea name="${key}">${esc(v)}</textarea></label>`;if(kind==='select')return `<label><span>${label}</span><select name="${key}">${opts.split('|').map(o=>`<option ${v===o?'selected':''}>${o}</option>`).join('')}</select></label>`;return `<label><span>${label}</span><input name="${key}" type="${kind}" value="${esc(Array.isArray(v)?v.join(', '):v)}"></label>`}).join('');$("#editor").dataset.row=JSON.stringify(row);$("#editor").showModal()}
$("#editorForm").addEventListener('submit',e=>{e.preventDefault();const row=JSON.parse($("#editor").dataset.row);for(const [key,,kind] of cfg[type].fields){const el=e.currentTarget.elements[key];let v=kind==='checkbox'?el.checked:el.value.trim();if(key==='distances')v=v?String(v).split(',').map(x=>x.trim()).filter(Boolean):[];if(kind==='number')v=v===''?null:Number(v);set(row,key,v)}if(editing===null)rows.unshift(row);else rows[editing]=row;RFContentStore.write(type,rows);$("#editor").close();render()});
$("#list").addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;for(const k of ['edit','toggle','delete'])if(b.dataset[k]!==undefined){const i=Number(b.dataset[k]);if(k==='edit')openEditor(i);if(k==='toggle'){rows[i].published=rows[i].published===false;RFContentStore.write(type,rows);render()}if(k==='delete'&&confirm('삭제할까요?')){rows.splice(i,1);RFContentStore.write(type,rows);render()}}});
document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-type]').forEach(x=>x.classList.remove('active'));b.classList.add('active');type=b.dataset.type;$("#search").value='';load()});
$("#search").oninput=render;$("#addNew").onclick=()=>openEditor();$("#resetType").onclick=()=>{if(confirm('현재 관리자 데이터를 지우고 기본 파일로 되돌릴까요?')){RFContentStore.clear(type);load()}};
$("#exportAll").onclick=()=>{const blob=new Blob([JSON.stringify(RFContentStore.exportAll(),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`runningfit-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};
$("#importAll").onchange=async e=>{const f=e.target.files[0];if(!f)return;try{RFContentStore.importAll(JSON.parse(await f.text()));await load();alert('가져오기 완료')}catch{alert('올바른 백업 JSON이 아닙니다.')}};load();
